drop table if exists roads;
drop table if exists caves;
drop table if exists mountains;
drop table if exists landmarks;
drop table if exists location_visits;
drop table if exists locations;
drop table if exists humans;
drop table if exists passports;
drop table if exists colors;
